load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "part1",
    srcs = ["part1.cc"],
    deps = [
        "//util:a_star",
        "//util:grid2",
        "//util:io",
        "@com_google_absl//absl/log:check",
    ],
)

cc_binary(
    name = "part2",
    srcs = ["part2.cc"],
    deps = [
        "//util:a_star",
        "//util:grid2",
        "//util:io",
        "@com_google_absl//absl/log:check",
    ],
)
